services:
  # The daemon service that controls the LED matrix and talks to Twitch
  daemon:
    build: .
    container_name: matrix_daemon
    privileged: true
    volumes:
      - /tmp:/tmp
      # Persist the token file on the host machine
      - ./twitch_tokens:/etc/twitch_matrix
      # Mount a volume for persistent logs
      - ./logs:/app/logs

  # The control panel service that runs the CherryPy web server
  control-panel:
    build: .
    container_name: matrix_control_panel
    command: ["python", "control_panel.py"]
    depends_on:
      - daemon
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
      # Mount a volume for persistent logs
      - ./logs:/app/logs